import type { Metadata } from "next";
import "./globals.css";
import FlyoutNav from "./components/Navbar";
import { Footerdemo } from "@/components/ui/footer-section";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <FlyoutNav />
        {children}
        <Footerdemo/>

      </body>
    </html>
  );
}
